services:
  postgres:
    container_name: howto-postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: howto-db
      POSTGRES_USER: howto
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/test/resources/db/baseline/:/docker-entrypoint-initdb.d