version: "3.1"

services:

  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: howto-db
      POSTGRES_USER: howto
      POSTGRES_PASSWORD: password