spring:
  application:
    name: howto
  profiles:
    default: dev
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: ${spring.application.name}
  version: @version@

howto:
  jwt-secret: super-obvious-secret-1-!
  url-haus:
    base-url: https://urlhaus-api.abuse.ch
    max-allowed-urls: 3

---

spring:
  config:
    activate:
      on-profile: integration-test
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/howto-db
    hikari:
      username: howto
      password: password
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration