spring:
  application:
    name: howto
  profiles:
    default: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: ${spring.application.name}
  version: @version@

---

spring:
  config:
    activate:
      on-profile: integration-test

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/howto-db
    hikari:
      username: howto
      password: password
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration