spring:
  application:
    name: howto
  profiles:
    default: local
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  name: ${spring.application.name}
  version: @version@

howto:
  jwt-secret: superObviousSecret0d8f64c2b3e7a8f928b7d439ab3qsdkfljh4gjkkjsdv4890KJSHJ4t9fsdnfo329045Kndmfam390245nvmslaq
  url-haus:
    base-url: https://urlhaus-api.abuse.ch
    max-allowed-urls: 3

---

spring:
  config:
    activate:
      on-profile: integration-test
  flyway:
    locations: classpath:/db/migration/common,classpath:/db/migration/local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/howto-db
    hikari:
      username: howto
      password: password
  flyway:
    locations: classpath:/db/migration/common,classpath:/db/migration/local
    out-of-order: true